### ISSUE TITLE
Installation failure in alpine linux (Docker)

### ISSUE THREAD

**Issue by blmayer** [jeroen/mongolite#131]
Hi, I can't build this package in alpine linux from docker, here's the stack's last lines:

```goc-openssl.o mongoc/mongoc-apm.o mongoc/mongoc-crypto.o mongoc/mongoc-crypto-openssl.o mongoc/mongoc-handshake.o mongoc/mongoc-stream-tls-openssl.o mongoc/mongoc-stream-tls-openssl-bio.o mongoc/mongoc-cluster-sasl.o mongoc/mongoc-cmd.o mongoc/mongoc-change-stream.o mongoc/mongoc-client-session.o mongoc/mongoc-cluster-cyrus.o mongoc/mongoc-compression.o mongoc/mongoc-cyrus.o mongoc/mongoc-write-command-legacy.o mongoc/mongoc-linux-distro-scanner.o
gcc -shared -L/usr/lib/R/lib -Wl,--as-needed -o mongolite.so bson.o client.o collection.o cursor.o hex.o mongo_log.o reader.o utils.o -Lmongoc -lstatmongoc -Lbson -lstatbson -lsasl2 -lssl -lcrypto -lresolv -lz -L/usr/lib/R/lib -lR
installing to /usr/lib/R/library/mongolite/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
Warning in file.copy(file.path(R.home("doc"), "html", "R.css"), outman) :
  problem copying /usr/share/doc/R/html/R.css to /usr/lib/R/library/mongolite/html/R.css: No such file or directory
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘mongolite’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/mongolite/libs/mongolite.so':
  Error relocating /usr/lib/R/library/mongolite/libs/mongolite.so: ASN1_STRING_get0_data: symbol not found
Error: loading failed
Execution halted
ERROR: loading failed```

I have all compilation utilities and:
- mongodb-3.4.10-r0 
- mongodb-tools-3.4.10-r0
- libressl-2.6.3-r0
- libressl-dev-2.6.3-r0

It seems to compile ok but it doesn't moves the library. Any advice?

Thanks in advance.

**Comment by jeroen** [comment]
Looks like you have conflicting copies of both openssl 1.0 and 1.1 installed on your machine

**Comment by jeroen** [comment]
Do you have more versions in /usr/local/lib ?

**Comment by blmayer** [comment]
```bash-4.4# ls /usr/local/lib/*ssl*
ls: /usr/local/lib/*ssl*: No such file or directory```

Nope.

**Comment by jeroen** [comment]
OK this was due to the openssl/libressl version chaos. It should be fixed in the next version of mongolite.

**Comment by RobertLowe** [comment]
not fixed
```
 ** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘mongolite’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/lib/R/library/00LOCK-mongolite/00new/mongolite/libs/mongolite.so':
  Error relocating /usr/lib/R/library/00LOCK-mongolite/00new/mongolite/libs/mongolite.so: res_ninit: symbol not found
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/lib/R/library/mongolite’
```


tried incrementally with:
apk add  libressl
apk add  libressl-dev
apk add libssl3
apk add  libssl1.1

```
 $ ls  /usr/lib/*ssl*
/usr/lib/libssl.a          /usr/lib/libssl.so.1.1     /usr/lib/libssl.so.50
/usr/lib/libssl.so         /usr/lib/libssl.so.3       /usr/lib/libssl.so.50.0.0

 $ usr/local/lib/*ssl*
bash: usr/local/lib/*ssl*: No such file or directory
```

cran nor master build @jeroen

**Comment by jeroen** [comment]
Thanks, this is another issue, probably related to the newly added aws-auth module.

**Comment by jeroen** [comment]
https://stackoverflow.com/questions/69479642/error-res-ninit-was-not-declared-in-this-scope-did-you-mean-res-init

**Comment by jeroen** [comment]
Can you try again from the master branch?
